### PR TITLE
Add link to reference docs in README

### PR DESCRIPTION
**Pull request by Leo-Ryu**
Hi there!

My name is Leo, a CS student at Brown building an automated platform for editable codebase documentation.

I generated documentation for this repository and placed a link in the README. Please feel free to try it out and let me know what you think!

### CODE REVIEW

**Review by pkuppens — COMMENTED** [review]
The newly added link points to some useless page with unrelated placeholder text about Flask.
So despite my 2-second enthusiasm, because I want to combine nnUNet with Flask, 
**_I don't get it._** 

The current location of the documentation seems fine to me. And otherwise, the link should point to already migrated and improved documentation..

**Comment by FabianIsensee** [comment]
Same here. I am a bit confused

**Comment by pkuppens** [comment]
He is pushing the same stuff in a lot of other repos as well..

Met vriendelijke groet,
Pieter Kuppens.


Op wo 9 dec. 2020 om 14:08 schreef Fabian Isensee <notifications@github.com

**Comment by FabianIsensee** [comment]
I see, he is building a website for documentation and would like us to try it. It's aggressive marketing :-D
I barely have the time to keep everything up to date as it is now, so there is unfortunately no way I can try this out at the moment

**Pull request closed without merging**
