### PR TITLE
Add sort_keys parameter to generate_dataset_json

### PR DESCRIPTION
**Pull request by Azumix**
Hey everyone!
Here is my attempt to Fix MIC-DKFZ/nnUNet#607. With the addition of this parameter (which default value is set to `True` to stick with what is in place at the moment, you can choose to sort or not the keys of the label dictionary. Note that, if you set it to `False` it is your responsibility to unsure that your labels are in a consecutive order.

### CODE REVIEW

**Comment by FabianIsensee** [comment]
How does this behave with more than 10 labels? If we support sorting then it should work all the time

**Comment by Azumix** [comment]
Hello!
Well, the parameter just enable/disable the sorting feature. So with the new fix you deployed today, which allow keys in int order instead of string it will just sort the keys if the parameter if set to `True` and don't sort it if it is set to `False`. Before your fix it allowed me to sort my keys on my side then call your function.

**Comment by FabianIsensee** [comment]
The keys will still be string. What I want to avoid is that if someone sorts their keys properly (1, 2, 3, 4, ..., 10, 11, 12) that this sorting will be messed up if sort_keys=True (1, 11, 12, 2, 3, 4, ....). This should not be the case

**Comment by Azumix** [comment]
That's exactly what I also wanted to avoid, as my keys where correctly sorted directly, in the end it was messed up by the integrated sorting. 
Thus, it is what is allowed here, if you have your keys that are already well sorted you just pass `sort_keys=False`, then the function will trust you and won't try to sort the keys and thus, it won't mess up everything.

**Comment by FabianIsensee** [comment]
ah now I see :-D

**Pull request merged**
