### PR TITLE
Modified documentation

### PR DESCRIPTION
**Pull request by monjoybme**
Modified documentation

### CODE REVIEW

**Comment by FabianIsensee** [comment]
It really doesn't matter what the folder is called. This is totally up to the users. So there isn't really a need to change this

**Comment by monjoybme** [comment]
@FabianIsensee In your documentation, you mentioned about ```nnUNet_raw_data_base``` folder [[link].](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/dataset_conversion.md) But [ [here],](https://github.com/MIC-DKFZ/nnUNet/blob/master/documentation/setting_up_paths.md) there is no information of ```nnUNet_raw_data_base``` path. New users initially will face a problem to find the path of ```nnUNet_raw_data_base```  folder. Hence, it will be easier for them to understand if you set the folder path with the correct naming format as required by this code.
Hence, please change as following:
 
```export nnUNet_raw_data_base="/media/fabian/nnUNet_raw```
to
```export nnUNet_raw_data_base="/media/fabian/nnUNet_raw_data_base```

**Comment by FabianIsensee** [comment]
OK then :see_no_evil:

**Comment by FabianIsensee** [comment]
I cannot merge this PR because your master has moved forward in the meantime and I don't want to merge your workstation-specific readme. You need to create a separate, clean (= only the intended changes) branch for this update and then make a PR from that branch.
nnunet is not hosted onto GitHub, it's just mirrored here. I cannot use the GitHub functionality for accpeting PRs

**Comment by monjoybme** [comment]
@FabianIsensee Thanks! Created a new PR.

**Pull request closed without merging**
