### PR TITLE
solving np.vstack numpy problem

### PR DESCRIPTION
**Pull request by victorcaquilpan**
I had a problem running the line 87 due to modifications in the behavior of the function np.vstack in Numpy.

Before:
return np.vstack(images, dtype=np.float32, casting='unsafe'), dict
Now:
return np.vstack(images).astype(np.float32, casting='unsafe'), dict

### CODE REVIEW

**Comment by FabianIsensee** [comment]
Hey can you please elaborate on what your problem with vstack is? We have not observed any problems here

**Comment by victorcaquilpan** [comment]
Newer version of numpy don't allow defining the dtype inside the vstack method. Then, to replace `np.vstack(images, dtype=np.float32, casting='unsafe')`, I need to change to `np.vstack(images).astype(np.float32, casting='unsafe')`. I am using numpy 1.24.4

**Comment by ancestor-mithril** [comment]
> Newer version of numpy don't allow defining the dtype inside the vstack method. Then, to replace `np.vstack(images, dtype=np.float32, casting='unsafe')`, I need to change to `np.vstack(images).astype(np.float32, casting='unsafe')`. I am using numpy 1.24.4

The dtype keyword was added in numpy 1.24: https://numpy.org/doc/1.24/reference/generated/numpy.vstack.html.
Older versions of numpy are already too old.

**Comment by FabianIsensee** [comment]
In that case the proper solution would be to require numpy>=1.24

**Comment by FabianIsensee** [comment]
I'll change that

**Pull request closed without merging**
